In [5]:
import lancedb
from dotenv import load_dotenv

load_dotenv()

db = lancedb.connect(uri="../knowledge_base")
db

LanceDBConnection(uri='c:\\Users\\mdsw8\\Documents\\MLOps\\MLOps & molnplattformar\\10_pydanticai_rags\\RAG_mlops25\\rag\\src\\rag\\explorations\\..\\knowledge_base')

In [6]:
db["articles"]

LanceTable(name='articles', version=31, _conn=LanceDBConnection(uri='c:\\Users\\mdsw8\\Documents\\MLOps\\MLOps & molnplattformar\\10_pydanticai_rags\\RAG_mlops25\\rag\\src\\rag\\explorations\\..\\knowledge_base'))

In [7]:
db["articles"].to_pandas()

,document_name,filepath,content,embedding
0,fisk.txt,C:\Users\mdsw8\Documents\MLOps\MLOps & molnpla...,Fiskar (Pisces) är en grupp vattenlevande rygg...,"[0.056915283, 0.020736694, -0.028640747, -0.04..."
1,kanin.txt,C:\Users\mdsw8\Documents\MLOps\MLOps & molnpla...,Harar och kaniner\n\nArtikel\nDiskussion\nLäs\...,"[-0.021514893, -0.024353027, 0.004486084, -0.0..."
2,krabba.txt,C:\Users\mdsw8\Documents\MLOps\MLOps & molnpla...,Krabbor (Brachyura) är en delordning av vatten...,"[0.011001587, -0.03274536, -0.04901123, -0.042..."
3,panda.txt,C:\Users\mdsw8\Documents\MLOps\MLOps & molnpla...,"Jättepanda (Ailuropoda melanoleuca), panda, pa...","[0.07885742, 0.018447876, -0.00818634, -0.0604..."
4,tiger.txt,C:\Users\mdsw8\Documents\MLOps\MLOps & molnpla...,Tiger (Panthera tigris) är ett kattdjur som en...,"[0.022979736, 0.03173828, -0.004386902, -0.050..."

In [8]:
db["articles"].search("vad äter pandor?").to_pandas()

,document_name,filepath,content,embedding,_distance
0,panda.txt,C:\Users\mdsw8\Documents\MLOps\MLOps & molnpla...,"Jättepanda (Ailuropoda melanoleuca), panda, pa...","[0.07885742, 0.018447876, -0.00818634, -0.0604...",0.806010
1,krabba.txt,C:\Users\mdsw8\Documents\MLOps\MLOps & molnpla...,Krabbor (Brachyura) är en delordning av vatten...,"[0.011001587, -0.03274536, -0.04901123, -0.042...",0.968142
2,tiger.txt,C:\Users\mdsw8\Documents\MLOps\MLOps & molnpla...,Tiger (Panthera tigris) är ett kattdjur som en...,"[0.022979736, 0.03173828, -0.004386902, -0.050...",0.989819
3,fisk.txt,C:\Users\mdsw8\Documents\MLOps\MLOps & molnpla...,Fiskar (Pisces) är en grupp vattenlevande rygg...,"[0.056915283, 0.020736694, -0.028640747, -0.04...",1.145338
4,kanin.txt,C:\Users\mdsw8\Documents\MLOps\MLOps & molnpla...,Harar och kaniner\n\nArtikel\nDiskussion\nLäs\...,"[-0.021514893, -0.024353027, 0.004486084, -0.0...",1.199905